ci: Fix workflow

diff --git a/.github/workflows/check-changeset.yml b/.github/workflows/check-changeset.yml
--- a/.github/workflows/check-changeset.yml
+++ b/.github/workflows/check-changeset.yml
@@ -5,16 +5,27 @@ on:
 
 jobs:
   check-changeset:
+    name: Check Changeset
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - uses: ./.github/actions/setup
 
       - name: Fetch origin main branch
         run: git fetch origin main
 
-      - name: Verify changeset exists
+      - name: Verify .changeset file exists
         run: |
-          if [ -z "$(git diff --name-only origin/main...HEAD | grep '.changeset')" ]; then
-            echo "No changeset found! Please add one."
+          echo "Checking for .changeset files..."
+
+          CHG_FILES=$(git diff --name-only origin/main...HEAD | grep '\.changeset' || true)
+
+          if [ -z "$CHG_FILES" ]; then
+            echo "::error title=Missing Changeset::No .changeset file found in this PR. Please generate one using 'pnpm changeset' and commit it."
             exit 1
           fi
+
+          echo "Changeset file(s) found:"
+          echo "$CHG_FILES"
